# Generated by Django 3.2.5 on 2022-05-12 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Categoría')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('ocupacionId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Ocupación')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idPelicula', models.AutoField(primary_key=True)),
                ('Titulo', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=200)),
                ('idIMDB', models.CharField(max_length=20)),
                ('Generos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.TextField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(help_text='Debe introducir una edad', verbose_name='Edad')),
                ('sexo', models.CharField(help_text='Debe elegir entre M o F', max_length=1, verbose_name='Sexo')),
                ('codigoPostal', models.TextField(verbose_name='Código Postal')),
                ('ocupacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ocupacion')),
            ],
            options={
                'ordering': ('idUsuario',),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('Puntuacion', models.IntegerField()),
                ('idPelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuaciones',
            field=models.ManyToManyField(through='main.Puntuacion', to='main.Usuario'),
        ),
    ]
